# type: ignore
# accounting/application/repositories.py

from accounting.domain.models import AccountingTransaction, TransactionLine, Account, User, Business


class TransactionRepository:
    def add(self, transaction: AccountingTransaction, lines: list[TransactionLine], user_id: int) -> int: ...

    def get_by_id(self, transaction_id: int) -> AccountingTransaction | None: ...

    def get_lines(self, transaction_id: int) -> list[TransactionLine]: ...

    def delete(self, transaction_id: int, user_id: int) -> None: ...


class AccountRepository:
    def add(self, account: Account) -> int: ...

    def get_by_id(self, account_id: int) -> Account | None: ...

    def get_by_number(self, business_id: int, account_number: int) -> Account | None: ...

    def get_for_business(self, business_id: int) -> list[Account]: ...


class UserRepository:
    def add(self, user: User) -> int: ...

    def get_by_id(self, user_id: int) -> User | None: ...

    def get_by_username(self, username: str) -> User | None: ...


class BusinessRepository:
    def add(self, business: Business) -> int: ...

    def get_by_id(self, business_id: int) -> Business | None: ...

    def get_all(self) -> list[Business]: ...
