name: Python Linting

on:
  push:
    branches:
      - '**'    # All branches
  pull_request:
    branches:
      - '**'    # All branches

jobs:
  lint:
    name: Run Black, Bandit, and Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements-dev.txt

      - name: Run Bandit (security check)
        run: |
          echo "Running Bandit..."
          bandit -r . -ll -iii

      - name: Run Ruff (linting)
        run: |
          echo "Running Ruff..."
          ruff check .
